---
- name: Create Couchpotato Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ docker_home }}/couchpotato/config"

- name: Couchpotato Docker Container
  docker_container:
    name: couchpotato
    image: linuxserver/couchpotato
    pull: true
    volumes:
      - "{{ couchpotato_config_directory }}:/config:rw"
downloads_root }}/completed:/downloads:rw"
movies_root }}:/movies:rw"
      - "{{ couchpotato_torrents_directory }}:/torrents:rw"
    ports:
      - "5050:5050"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ couchpotato_user_id }}"
      PGID: "{{ couchpotato_group_id }}"
    restart_policy: unless-stopped
    memory: 1g