- name: Create get_iplayer Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ get_iplayer_config_directory }}"
downloads_root }}"

- name: get_iplayer Docker Container
  docker_container:
    name: get_iplayer
    image: kolonuk/get_iplayer
    pull: true
    volumes:
      - "{{ get_iplayer_config_directory }}:/root/.get_iplayer:rw"
downloads_root }}:/root/output:rw"
    ports:
      - "8182:8181"
    restart_policy: unless-stopped
    memory: 1g

