---
- name: Create nzbget Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ nbzget_config_directory }}"
downloads_root }}"

- name: nzbget Docker Container
  docker_container:
    name: nzbget
    image: linuxserver/nzbget
    pull: true
    volumes:
      - "{{ nbzget_config_directory }}:/config:rw"
downloads_root }}:/downloads:rw"
    ports:
      - "6789:6789"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ nbzget_user_id }}"
      PGID: "{{ nbzget_group_id }}"
    restart_policy: unless-stopped
    memory: 1g

