---
- name: Create Radarr Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ radarr_data_directory }}"

- name: Radarr
  docker_container:
    name: radarr
    image: linuxserver/radarr
    pull: true
    volumes:
movies_root }}:/movies:rw"
downloads_root }}:/downloads:rw"
      - "{{ radarr_data_directory }}:/config:rw"
    ports:
      - "7878:7878"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ radarr_user_id }}"
      PGID: "{{ radarr_group_id }}"
    restart_policy: unless-stopped
    memory: 1g
